swagger: "2.0"
info:
  version: "0.0.1"
  title: Guest Account API
host: mocktarget.apigee.net
basePath: /v1/guestAccounts
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
   '/{accountId}':
     get:
      description: Get account info for a given accountId.
      parameters:
        - name: accountId
          in: path
          required: true         
          type: string
        - name: password
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AccountInfoResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  AccountInfoResponse:
    required:
      - accountId
    properties:
      accountId:
       type: string
      consumerId:
       type: string
      firstName:
       type: string
      lastName:
       type: string
      email:
       type: string
      brand:
       type: char
  ErrorResponse:
    required:
      - code   
      - message
    properties:
      code:
        type: string
      message:
        type: string