swagger: "2.0"
info:
  version: "1.0.0"
  title: Security Questions API
host: mocktarget.apigee.net
basePath: /v1/guestAccounts
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
   '/securityQuestions':
     get:
      description: A service to retrieve a list of security questions.
      parameters:
        - name: email
          in: query
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
              $ref: '#/definitions/securityQ'
        "422":
          description: Unprocessable entry
          schema:
              $ref: '#/definitions/errorUnprocessable'      
        default:
          description: Error payload
          schema:
              $ref: '#/definitions/error'
definitions:
  securityQ:
    type: object
    properties:
      securityQuestions: 
        type: array
        items:
          $ref: '#/definitions/questions'
  questions:
    type: object
    properties:
      question:
        type: string
        example: "What is the name of your first dog?"
  errorUnprocessable:
    type: object
    required:
      - message
    properties:
      message:
        type: string      
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string       
