swagger: "2.0"
info:
  version: "1.0.0"
  title: Validate Security Question & Answer API
host: mocktarget.apigee.net
basePath: /v1/guestAccounts
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
   /{emailId}/securityQuestions/validation:
     get:
      description: A service to validate security question and answer.
      parameters:
        - name: emailId
          in: path
          required: true
          type: string
          format: string
        - name: question
          in: query
          required: true
          type: array
          items:
           type: string
        - name: answer
          in: query
          required: true
          type: array
          items:
           type: string   
      responses:
        '200':
          description: OK
          schema:
              $ref: '#/definitions/response'
        "422":
          description: Unprocessable entry
          schema:
              $ref: '#/definitions/errorUnprocessable'      
        default:
          description: Error payload
          schema:
              $ref: '#/definitions/error'
definitions:
  response:
    type: object
    required:
      - isValid
    properties:
      isValid:
        type: boolean
  errorUnprocessable:
    type: object
    required:
      - message
    properties:
      message:
        type: string      
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string       