# UCM Consumer Create/Update Spec.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: 1.0.0
  title: <PostConsumer>
  termsOfService: http://rccl.com/terms/
  contact: 
    name: GuestAccount team
    url: http://rccl.io
  license:
    name: RCCL
    url: http://rccl.com/licenses/by/1.0/
#basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json  
#host: '10.16.6.134:8090'
# Describe your paths here
paths:
  /guestProfiles:
    put:
      tags:
        - guestProfile
      description: | 
         Service to create/update the consumer in UCM.
      operationId: updateConsumer
      produces:
        - application/json    
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            $ref: '#/definitions/PersonalInfo'  
          
      # Expected responses for this operation:
      responses:
        # Response code
        "200":
          description: Successful response
          schema:
              $ref: '#/definitions/consumerData'
        "422":
          description: Unprocessable entry
          schema:
              $ref: '#/definitions/errorUnprocessable'      
        default:
          description: Error payload
          schema:
              $ref: '#/definitions/error'      
          # A schema describing your response object.
          # Use JSON Schema format
          #examples:
            #application/json:
              #{consumerData: {consumerId: 16398698}}
                
definitions:
  PersonalInfo:
            #$ref: "#/definitions/PersonalInfo"
    type: object
    properties:
      personalInfo:
        $ref: "#/definitions/PersonalIn"
      addresses:
        type: array
        items:
          $ref: "#/definitions/Addresses"
      contacts:
          $ref: "#/definitions/Contacts"
  PersonalIn:
    type: object
    required:
      - firstName
      - lastName
      - email
      - vdsAccountId
    properties:
      firstName:
        type: string
        example: AlppHH
      lastName:
        type: string
        example: PriuHH
      email: 
        type: string
        example: AlppHH@PriuHH.com
      vdsAccountId:
        type: string
        example: B2C
      birthDate:
        type: string
        example: "1960-02-08"
      consumerId:
        type: string
        example: "90920730"
      gender:
        type: string
        example: "Female"        
  consumerData:
    type: object
    required:
      - consumerId
    properties:
      consumerId:
        type: string
  Addresses:
    type: object
    properties:
      type:
        type: string
        example: "1"
      address:
        type: string
        example: "9771 NE 194 St"
      city:
        type: string
        example: "Aventura"
      stateCode:
        type: string
        example: "FL"
      postalCode:
        type: string
        example: "33180"
      countryCode:
        type: string
        example: "USA"
  Contacts:
    type: object
    properties:
      telephoneNumber:
        type: string
        example: "209917710099"
      telephoneType:
        type: string
        example: "1"
  errorUnprocessable:
    type: object
    required:
      - message
    properties:
      message:
        type: string      
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string      