# UCM Consumer Create/Update Spec.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: 1.0.0
  title: Validate Security Question & Answer API
host: mocktarget.apigee.net
basePath: /v1/guestAccounts
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
# Describe your paths here
paths:
  /securityQuestions/validation:
    post:
      description: A service to validate security question and answer.
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            $ref: '#/definitions/RequestObject'  
          
      # Expected responses for this operation:
      responses:
        '200':
          description: OK
          schema:
              $ref: '#/definitions/response'
        "422":
          description: Unprocessable entry
          schema:
              $ref: '#/definitions/errorUnprocessable'      
        default:
          description: Error payload
          schema:
              $ref: '#/definitions/error'
          
definitions:
  RequestObject:
    type: object
    properties:
      emailId:
        type: string
        example: "carol.blue@gmail.com"
      securityQuestionAnswer:
        type: array
        items:
          $ref: "#/definitions/SecurityQuestionAnswer"
  SecurityQuestionAnswer:
    type: object
    properties:
      question:
        type: string
        example: "Who was your first kiss?"
      answer:
        type: string
        example: "kiss"
  response:
    type: object
    required:
      - isValid
    properties:
      isValid:
        type: boolean
  errorUnprocessable:
    type: object
    required:
      - message
    properties:
      message:
        type: string      
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string      