swagger: "2.0"
info:
  version: "0.0.1"
  title: GuestAccount API
host: http://mocktarget.apigee.net
basePath: /v1/guestAccounts/:vdsId
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
   '/':
     put:
      description: Reset account password for a given vdsId.
      parameters:
        - name: body
          description: A new `AccountPassword`
          in: body
          schema:
            $ref: '#/definitions/ResetAccountPasswordRequest'
        - name: vdsId
          in: path
          required: true
          description: VDS Id
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResetAccountPasswordResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
ResetAccountPasswordRequest:
  required:
    - password
    - oldPassword
	properties:
    password:
     type: alphanumeric
    oldPassword:
     type: alphanumeric
    firstName:
     type: string
    lastName:
     type: string
    email:
     type: string
    brand:
     type: char
ResetAccountPasswordResponse:
  required:
    - consumerId
    - vdsId
	properties:
    consumerId:
      type: string
    vdsId:
      type: string
ErrorResponse:
  required:
    - code   
    - message
  properties:
    code:
      type: string
    message:
      type: string
